color0 #110f18
color1 #ff6767
color2 #61ffca
color3 #ffca85
color4 #a277ff
color5 #a277ff
color6 #61ffca
color7 #edecee
color8 #4d4d4d
color9 #ff6767
color10 #61ffca
color11 #ffca85
color12 #a277ff
color13 #a277ff
color14 #61ffca
color15 #edecee

cursor                #a277ff
cursor_text_color     #15141b
background            #15141b
foreground            #edecee
selection_foreground  #edecee
selection_background  #29263c
active_border_color   #a277ff
inactive_border_color #29263c
url_color             #a277ff

active_tab_foreground   #15141b
active_tab_background   #a277ff
inactive_tab_foreground #edecee
inactive_tab_background #29263c
cursor_trail_color      #edecee
